name: auto_wallet2
description: "A mobile application for managing vehicle expenses and events."
publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  table_calendar: ^3.0.9
  # flutter_local_notifications: ^14.1.5
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  flutter_datetime_picker_plus: ^2.1.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #   - assets/logo/app_logo.png # Example path for logo